### ISSUE TITLE
albert_barabasi node degrees

### ISSUE THREAD

**Issue by riccardomarabini** [VictorSeven/CNetwork#3]
Good afternoon, 
I am an undergraduate in Physics, and I am finding your work extremely stimulating. I am interested in simulating a transport network, hence the default Albert Barabasi generator really caught my eye. However, when I try to create a simple graph with the following parameters
    int n = 30; 
    int m0 = 7;
    int m = 4;  
and I print the degree of each node, they are all smaller than the minimum degree of the inner core, which should be m0: I expected to have at least m0 nodes with a degree higher than m0, as they should be at least all connected to one another. In addition, 
I thought that the degree of each smaller node would be equals to m, m=4 in my example, but I get nodes with only two or three links. 
I report the following errors in the SparseMatrix file
	"message": "\"data\" is ambiguous",
	"startLineNumber": 245,
	"startColumn": 39,
	"endLineNumber": 245,
	"endColumn": 43
the other messages relate to the same problem.
I thank you in advance for your attention,
your sincerely,

Riccardo Marabini

**Comment by VictorSeven** [comment]
Hi Riccardo, 

Sorry for the very slow response. I did not notice the issue opening until very recently.  And thank you very much for your interest in the library!

You are right, some of the changes to the codebase broke some stuff. Basically, the problem is that the function for Albert Barabasi was using always the directed network backend. I have fixed it and now it seems to work. I also added a similar fix to the degree_distribution function that was suffering from the same issue. I realise I will have to update also the configurational model, but that may take more time and I leave it as future work. To be fair, I did some big rewriting some time ago but there are many functions I very sparsely use, so there could be some small bugs here and there...  However, I've been fixing them over time.

So the thing should be basically fixed. Please feel free to reopen the issue if you find more problems or to open a new one if there's something else :) Thank you!

**Comment by riccardomarabini** [comment]
Hi Victor,
it is great to hear you have fixed the issue. I am slightly snowed under with some exams at the moment, hence I will not be able to inspect the changes in the network I was studying, in the short period.
In any case, I must thank you for your commitment and dedication,
Yours Faithfully

Riccardo Marabini

Da: Victor ***@***.***>
Inviato: mercoledì 8 marzo 2023 14:29
A: ***@***.***>
Cc: Riccardo Maria Marabini - ***@***.******@***.***>; ***@***.***>
Oggetto: Re: [VictorSeven/CNetwork] albert_barabasi node degrees (Issue #3)


Hi Riccardo,

Sorry for the very slow response. I did not notice the issue opening until very recently. And thank you very much for your interest in the library!

You are right, some of the changes to the codebase broke some stuff. Basically, the problem is that the function for Albert Barabasi was using always the directed network backend. I have re-checked it and now it seems to work. I also added a similar fix to the degree_distribution function that was suffering from the same issue. I realise I will have to update also the configurational model, but that may take more time and I leave it as future work. To be fair, I did some big rewriting some time ago but there are many functions I very sparsely use, so there could be some small bugs here and there... However, I've been fixing them over time.

So the thing should be basically fixed. Please feel free to reopen the issue if you find more problems or to open a new one if there's something else :) Thank you!
